# Generated by Django 3.0.3 on 2020-03-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_avatar', models.ImageField(blank=True, height_field=40, upload_to='userpage', width_field=30)),
                ('user_age', models.DateField()),
                ('user_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
