# Generated by Django 3.0.3 on 2020-03-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='user_avatar',
        ),
    ]
