# Generated by Django 3.0.3 on 2020-03-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0002_remove_interface_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterFace',
        ),
    ]
