# Generated by Django 3.0.3 on 2020-03-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grp', '0003_delete_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватар')),
                ('user_self', models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе')),
                ('user_birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
