# Generated by Django 3.0.3 on 2020-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_self',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[['male', 'Мужской'], ['female', 'Женский']], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[['none', 'Не определенно'], ['single', 'Холост'], ['in_a_rel', 'В отношениях'], ['engaged', 'Помолвлен(а)'], ['married', 'Женат/Замужем'], ['in_love', 'Влюблен(а)'], ['complicated', 'Все сложно']], default='none', max_length=20, verbose_name='Статус отношений'),
        ),
    ]
