# Generated by Django 3.0.3 on 2020-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0007_auto_20200310_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_surname',
            field=models.TextField(blank=True, null=True, verbose_name='Фамилия'),
        ),
    ]
