# Generated by Django 3.0.3 on 2020-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0008_auto_20200311_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.TextField(max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_surname',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Фамилия'),
        ),
    ]
