# Generated by Django 3.0.3 on 2020-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0009_auto_20200311_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_surname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия'),
        ),
    ]
