# Generated by Django 3.0.3 on 2020-03-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0010_auto_20200311_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship',
        ),
    ]
