# Generated by Django 3.0.3 on 2020-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0013_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_cicle_first_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало последнего цикла'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_cicle_last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание последнего цикла'),
        ),
    ]
