# Generated by Django 3.0.3 on 2020-03-22 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grp', '0014_auto_20200322_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_cicle_first_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_cicle_last_date',
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cicle_first_date', models.DateField(blank=True, null=True, verbose_name='Начало последнего цикла')),
                ('last_cicle_last_date', models.DateField(blank=True, null=True, verbose_name='Окончание последнего цикла')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
