# Generated by Django 3.0.3 on 2020-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0016_auto_20200323_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
