# Generated by Django 3.0.3 on 2020-03-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0019_auto_20200323_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grp.Profile', verbose_name='Пользователь'),
        ),
    ]
